<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" />';
echo '';
echo '<meta name="twitter:card" content="summary_large_image" />';
echo '<meta name="twitter:image:src" content="" />';
echo '<meta property="og:image" content="" />';
echo '<meta name="twitter:title" content="LeanBiome" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />';
echo '<link rel="shortcut icon" href="assets/images/favicon-2-128x128.png" type="image/x-icon" />';
echo '<meta name="description" content="Support Natural Weight Loss With LeanBiome, Formulated Using The Latest Ivy League Research, And Backed By Real-World Results." />';
echo '';
echo '<title>LeanBiome</title>';
echo '<link rel="stylesheet" href="assets/web/assets/mobirise-icons2/mobirise2.css" />';
echo '<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css" />';
echo '<link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css" />';
echo '<link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css" />';
echo '<link rel="stylesheet" href="assets/animatecss/animate.css" />';
echo '<link rel="stylesheet" href="assets/dropdown/css/style.css" />';
echo '<link rel="stylesheet" href="assets/socicon/css/styles.css" />';
echo '<link rel="stylesheet" href="assets/theme/css/style.css" />';
echo '<link rel="preload" href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'" />';
echo '<noscript><link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"';
echo '/></noscript>';
echo '<link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css" />';
echo '<link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css" />';
echo '</head>';
echo '';
echo '<body>';
echo '<section data-bs-version="5.1" class="menu menu2 cid-tjymvQa5kp" once="menu" id="menu2-15">';
echo '<nav class="navbar navbar-dropdown navbar-expand-lg">';
echo '<div class="container">';
echo '<div class="navbar-brand">';
echo '<span class="navbar-caption-wrap"><a class="navbar-caption text-white display-2" href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '>LeanBiome™</a';
echo '></span';
echo '>';
echo '</div>';
echo '<button';
echo 'class="navbar-toggler"';
echo 'type="button"';
echo 'data-toggle="collapse"';
echo 'data-bs-toggle="collapse"';
echo 'data-target="#navbarSupportedContent"';
echo 'data-bs-target="#navbarSupportedContent"';
echo 'aria-controls="navbarNavAltMarkup"';
echo 'aria-expanded="false"';
echo 'aria-label="Toggle navigation"';
echo '>';
echo '<div class="hamburger">';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '</div>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarSupportedContent">';
echo '<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">';
echo '<li class="nav-item">';
echo '<a class="nav-link link text-white display-4" href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f">About LeanBiome</a';
echo '>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a';
echo 'class="nav-link link text-white display-4"';
echo 'href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '>How It Works?</a';
echo '>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a';
echo 'class="nav-link link text-white display-4"';
echo 'href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '>Pricing</a';
echo '>';
echo '</li>';
echo '</ul>';
echo '';
echo '<div class="navbar-buttons mbr-section-btn">';
echo '<a class="btn btn-warning display-4" href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '><span';
echo 'class="socicon socicon-bale mbr-iconfont mbr-iconfont-btn"';
echo 'style="font-size: 20px"';
echo '></span';
echo '>ORDER NOW</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</section>';
echo '';
echo '<section';
echo 'data-bs-version="5.1"';
echo 'class="header14 cid-tjtZOTAcVk"';
echo 'id="header14-k"';
echo '>';
echo '<div class="container">';
echo '<div class="row justify-content-center align-items-center">';
echo '<div class="col-12 col-md-6 image-wrapper">';
echo '<img';
echo 'src="assets/images/leanbiome-supplement-600x521.png"';
echo 'alt="Buy Now"';
echo '/>';
echo '</div>';
echo '<div class="col-12 col-md">';
echo '<div class="text-wrapper">';
echo '<h1 class="mbr-section-title mbr-fonts-style mb-3 display-2">';
echo '<strong>LeanBiome™ Official</strong><strong><br />';
echo '</h1>';
echo '<p class="mbr-text mbr-fonts-style display-7">';
echo '<br />Support Natural Weight Loss With LeanBiome, Formulated';
echo 'Using The Latest Ivy League Research, And Backed By Real-World';
echo 'Results.<br /><br />Formula Is Easy To Take Each Day, And Uses';
echo 'Only The Best &amp;&nbsp;<br /><strong';
echo '>100% Natural Ingredients</strong';
echo '>';
echo 'To Achieve Desired Results.<br /><br />';
echo '</p>';
echo '<div class="mbr-section-btn mt-3">';
echo '<a class="btn btn-warning display-4" href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '><span';
echo 'class="mobi-mbri mobi-mbri-arrow-next mbr-iconfont mbr-iconfont-btn"';
echo 'style="font-size: 15px"';
echo '></span';
echo '><font face="Moririse2"><br /></font>GET A DISCOUNT</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section';
echo 'data-bs-version="5.1"';
echo 'class="content4 cid-tjtCjTlHWT"';
echo 'id="content4-a"';
echo '>';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="title col-md-12 col-lg-12">';
echo '<h3';
echo 'class="mbr-section-title mbr-fonts-style align-center mb-4 display-2"';
echo '>';
echo '<strong>Limited Time Special Pricing - Act Now!</strong>';
echo '</h3>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section data-bs-version="5.1" class="image3 cid-tjufRGoCIV" id="image3-l">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-12 col-lg-10">';
echo '<div class="image-wrapper">';
echo '<a href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"';
echo '><img';
echo 'src="assets/images/leanbiome-order-1297x818.png"';
echo 'alt="Order"';
echo '/></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section data-bs-version="5.1" class="content4 cid-tjtKMEmhHh" id="content4-h">';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="title col-md-12 col-lg-12">';
echo '<h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2">';
echo '<strong>180-Days Money Back Guarantee</strong>';
echo '</h3>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section data-bs-version="5.1" class="header11 cid-tjtKXxqvPZ" id="header11-j">';
echo '<div class="container-fluid">';
echo '<div class="row justify-content-center">';
echo '<div class="col-12 col-md-5 image-wrapper">';
echo '<img class="w-100" src="assets/images/180-days-moneyback-guarantee-680x450.png" alt="Money Back Guarantee" />';
echo '</div>';
echo '<div class="col-12 col-md">';
echo '<div class="text-wrapper text-center">';
echo '<p class="mbr-text mbr-fonts-style display-7">';
echo 'The LeanBiome supplement is backed by a 100% money back guarantee for 180 full days from your original purchase.';
echo '<br />';
echo '<br />If you’re not totally and completely satisfied with the LeanBiome Supplement, or your experience in the first 180 days from your purchase simply let us know at LeanBiome portal and we’ll give you a refund within 48 hours';
echo 'of the product being returned.';
echo '<br />';
echo '<br />That’s right, simply return the LeanBiome supplement, even empty bottles, anytime within 180 days of your purchase and you’ll receive a refund, no questions asked!';
echo '</p>';
echo '<div class="mbr-section-btn mt-3">';
echo '<a class="btn btn-warning display-7" href="https://alxs7.bemobtrcks.com/go/2d85b103-980c-443f-bdbd-44206d6e511f"><span';
echo 'class="mobi-mbri mobi-mbri-arrow-next mbr-iconfont mbr-iconfont-btn"';
echo 'style="font-size: 15px"';
echo '></span';
echo '>GET YOUR BOTTLE TODAY</a';
echo '>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
?>